# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RevE.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(740, 853)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(30, 118, 681, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_EW = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_EW.setGeometry(QtCore.QRect(60, 10, 61, 21))
        self.lineEdit_EW.setObjectName("lineEdit_EW")
        self.lineEdit_FW = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_FW.setGeometry(QtCore.QRect(400, 10, 61, 21))
        self.lineEdit_FW.setObjectName("lineEdit_FW")
        self.lineEdit_PW = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_PW.setGeometry(QtCore.QRect(240, 10, 61, 21))
        self.lineEdit_PW.setObjectName("lineEdit_PW")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(130, 10, 21, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(310, 10, 21, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(470, 10, 21, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(180, 10, 51, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(360, 10, 31, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(500, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 98, 101, 16))
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(30, 170, 121, 16))
        self.label_9.setObjectName("label_9")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(30, 30, 251, 61))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.comboBox_Config = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_Config.setGeometry(QtCore.QRect(20, 5, 201, 26))
        self.comboBox_Config.setEditable(True)
        self.comboBox_Config.setMaxVisibleItems(13)
        self.comboBox_Config.setObjectName("comboBox_Config")
        self.comboBox_Config.addItem("")
        self.comboBox_Config.addItem("")
        self.comboBox_Config.addItem("")
        self.comboBox_Engine = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_Engine.setGeometry(QtCore.QRect(63, 32, 111, 26))
        self.comboBox_Engine.setEditable(True)
        self.comboBox_Engine.setMaxVisibleItems(13)
        self.comboBox_Engine.setObjectName("comboBox_Engine")
        self.comboBox_Engine.addItem("")
        self.comboBox_Engine.addItem("")
        self.comboBox_Engine.addItem("")
        self.pushButton_Exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_Exit.setGeometry(QtCore.QRect(320, 810, 91, 31))
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(310, 10, 51, 16))
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(30, 10, 91, 21))
        self.label_11.setObjectName("label_11")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(30, 440, 681, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.textEdit_Report = QtWidgets.QTextEdit(self.tab_7)
        self.textEdit_Report.setGeometry(QtCore.QRect(10, 10, 651, 301))
        self.textEdit_Report.setObjectName("textEdit_Report")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsViewFuel = QtWidgets.QGraphicsView(self.tab)
        self.graphicsViewFuel.setGeometry(QtCore.QRect(10, 10, 651, 281))
        self.graphicsViewFuel.setObjectName("graphicsViewFuel")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsViewRange = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsViewRange.setGeometry(QtCore.QRect(10, 10, 651, 281))
        self.graphicsViewRange.setObjectName("graphicsViewRange")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.graphicsViewTime = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsViewTime.setGeometry(QtCore.QRect(10, 10, 651, 291))
        self.graphicsViewTime.setObjectName("graphicsViewTime")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.tab_8)
        self.openGLWidget.setGeometry(QtCore.QRect(9, 9, 651, 301))
        self.openGLWidget.setObjectName("openGLWidget")
        self.tabWidget.addTab(self.tab_8, "")
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(30, 190, 181, 231))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_21 = QtWidgets.QLabel(self.frame_4)
        self.label_21.setGeometry(QtCore.QRect(21, 100, 41, 21))
        self.label_21.setObjectName("label_21")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(7, 10, 71, 21))
        self.label_13.setObjectName("label_13")
        self.lineEdit_AS = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_AS.setGeometry(QtCore.QRect(71, 73, 71, 21))
        self.lineEdit_AS.setObjectName("lineEdit_AS")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(10, 46, 71, 21))
        self.label_17.setObjectName("label_17")
        self.lineEdit_AF = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_AF.setGeometry(QtCore.QRect(71, 100, 71, 21))
        self.lineEdit_AF.setObjectName("lineEdit_AF")
        self.comboBox_Leg = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_Leg.setGeometry(QtCore.QRect(75, 10, 91, 26))
        self.comboBox_Leg.setObjectName("comboBox_Leg")
        self.comboBox_Leg.addItem("")
        self.comboBox_Leg.addItem("")
        self.comboBox_Leg.addItem("")
        self.comboBox_Leg.addItem("")
        self.comboBox_Leg.addItem("")
        self.comboBox_Leg.addItem("")
        self.comboBox_Leg.addItem("")
        self.label_20 = QtWidgets.QLabel(self.frame_4)
        self.label_20.setGeometry(QtCore.QRect(21, 72, 41, 21))
        self.label_20.setObjectName("label_20")
        self.pushButton_AddLeg = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_AddLeg.setGeometry(QtCore.QRect(50, 190, 113, 32))
        self.pushButton_AddLeg.setObjectName("pushButton_AddLeg")
        self.label_28 = QtWidgets.QLabel(self.frame_4)
        self.label_28.setGeometry(QtCore.QRect(150, 71, 41, 21))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_4)
        self.label_29.setGeometry(QtCore.QRect(150, 100, 41, 21))
        self.label_29.setObjectName("label_29")
        self.label_34 = QtWidgets.QLabel(self.frame_4)
        self.label_34.setGeometry(QtCore.QRect(150, 160, 41, 21))
        self.label_34.setObjectName("label_34")
        self.lineEdit_LT = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_LT.setGeometry(QtCore.QRect(71, 160, 71, 21))
        self.lineEdit_LT.setObjectName("lineEdit_LT")
        self.label_24 = QtWidgets.QLabel(self.frame_4)
        self.label_24.setGeometry(QtCore.QRect(10, 120, 131, 41))
        self.label_24.setObjectName("label_24")
        self.frame_5 = QtWidgets.QFrame(Dialog)
        self.frame_5.setGeometry(QtCore.QRect(289, 29, 421, 71))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(149, 30, 16, 41))
        self.label_23.setObjectName("label_23")
        self.lineEdit_Voltage = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_Voltage.setGeometry(QtCore.QRect(89, 40, 51, 21))
        self.lineEdit_Voltage.setObjectName("lineEdit_Voltage")
        self.label_22 = QtWidgets.QLabel(self.frame_5)
        self.label_22.setGeometry(QtCore.QRect(18, 30, 61, 41))
        self.label_22.setObjectName("label_22")
        self.label_25 = QtWidgets.QLabel(self.frame_5)
        self.label_25.setGeometry(QtCore.QRect(148, 10, 41, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_5)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_26.setObjectName("label_26")
        self.lineEdit_Capacity = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_Capacity.setGeometry(QtCore.QRect(89, 10, 51, 21))
        self.lineEdit_Capacity.setObjectName("lineEdit_Capacity")
        self.label_30 = QtWidgets.QLabel(self.frame_5)
        self.label_30.setGeometry(QtCore.QRect(280, 60, 61, 41))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_5)
        self.label_31.setGeometry(QtCore.QRect(215, 4, 71, 41))
        self.label_31.setObjectName("label_31")
        self.lineEdit_DischargeRate = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_DischargeRate.setGeometry(QtCore.QRect(300, 24, 51, 21))
        self.lineEdit_DischargeRate.setObjectName("lineEdit_DischargeRate")
        self.label_32 = QtWidgets.QLabel(self.frame_5)
        self.label_32.setGeometry(QtCore.QRect(360, 14, 16, 41))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.frame_5)
        self.label_33.setGeometry(QtCore.QRect(230, 20, 71, 41))
        self.label_33.setObjectName("label_33")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(230, 190, 481, 231))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_Run = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_Run.setGeometry(QtCore.QRect(200, 190, 91, 31))
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.textEdit_Current = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_Current.setGeometry(QtCore.QRect(10, 13, 461, 171))
        self.textEdit_Current.setObjectName("textEdit_Current")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(230, 170, 141, 16))
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit_EW.setText(_translate("Dialog", "50"))
        self.lineEdit_FW.setText(_translate("Dialog", "13"))
        self.lineEdit_PW.setText(_translate("Dialog", "5"))
        self.label_2.setText(_translate("Dialog", "lbs"))
        self.label_3.setText(_translate("Dialog", "lbs"))
        self.label_4.setText(_translate("Dialog", "lbs"))
        self.label_5.setText(_translate("Dialog", "Empty:"))
        self.label_6.setText(_translate("Dialog", "Payload:"))
        self.label_7.setText(_translate("Dialog", "Fuel:"))
        self.label_8.setText(_translate("Dialog", "(Maximum for Mugin: 13.4 lbs)"))
        self.label.setText(_translate("Dialog", "Aircraft Weights"))
        self.label_9.setText(_translate("Dialog", "Mission Leg Details"))
        self.comboBox_Config.setItemText(0, _translate("Dialog", "Mugin with 1 propeller"))
        self.comboBox_Config.setItemText(1, _translate("Dialog", "Mugin with 3 propellers"))
        self.comboBox_Config.setItemText(2, _translate("Dialog", "Dodecacopter"))
        self.comboBox_Engine.setCurrentText(_translate("Dialog", "K45 - TP"))
        self.comboBox_Engine.setItemText(0, _translate("Dialog", "K45 - TP"))
        self.comboBox_Engine.setItemText(1, _translate("Dialog", "K60 - TP"))
        self.comboBox_Engine.setItemText(2, _translate("Dialog", "K100 - TP"))
        self.pushButton_Exit.setText(_translate("Dialog", "Exit"))
        self.label_12.setText(_translate("Dialog", "Battery"))
        self.label_11.setText(_translate("Dialog", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "Output Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Fuel Burn"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Range"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Dialog", "Mission Profile"))
        self.label_21.setText(_translate("Dialog", "Finish"))
        self.label_13.setText(_translate("Dialog", "Leg Type"))
        self.lineEdit_AS.setText(_translate("Dialog", "0"))
        self.label_17.setText(_translate("Dialog", "Altitude:"))
        self.lineEdit_AF.setText(_translate("Dialog", "0"))
        self.comboBox_Leg.setItemText(0, _translate("Dialog", "Takeoff roll"))
        self.comboBox_Leg.setItemText(1, _translate("Dialog", "Constant speed climb"))
        self.comboBox_Leg.setItemText(2, _translate("Dialog", "Subsonic cruise"))
        self.comboBox_Leg.setItemText(3, _translate("Dialog", "Payload delivery"))
        self.comboBox_Leg.setItemText(4, _translate("Dialog", "Loiter"))
        self.comboBox_Leg.setItemText(5, _translate("Dialog", "Constant speed descent"))
        self.comboBox_Leg.setItemText(6, _translate("Dialog", "Landing"))
        self.label_20.setText(_translate("Dialog", "Start"))
        self.pushButton_AddLeg.setText(_translate("Dialog", "Add Leg"))
        self.label_28.setText(_translate("Dialog", "ft"))
        self.label_29.setText(_translate("Dialog", "ft"))
        self.label_34.setText(_translate("Dialog", "sec"))
        self.lineEdit_LT.setText(_translate("Dialog", "0"))
        self.label_24.setText(_translate("Dialog", "Loiter Time (optional):"))
        self.label_23.setText(_translate("Dialog", "V"))
        self.lineEdit_Voltage.setText(_translate("Dialog", "44.4"))
        self.label_22.setText(_translate("Dialog", "Voltage:"))
        self.label_25.setText(_translate("Dialog", "mAh"))
        self.label_26.setText(_translate("Dialog", "Capacity:"))
        self.lineEdit_Capacity.setText(_translate("Dialog", "5000"))
        self.label_30.setText(_translate("Dialog", "Voltage:"))
        self.label_31.setText(_translate("Dialog", "Discharge"))
        self.lineEdit_DischargeRate.setText(_translate("Dialog", "60"))
        self.label_32.setText(_translate("Dialog", "C"))
        self.label_33.setText(_translate("Dialog", "Rate:"))
        self.pushButton_Run.setText(_translate("Dialog", "Run!"))
        self.label_10.setText(_translate("Dialog", "Current Mission Profile"))

